export default function Head() {
  return (
    <>
      <meta charSet="UTF-8" />
      <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      <meta name="description" content="Messenger CLONE. Generated by create-t3-app" />
      <link href="/favicon.ico" rel="shortcut icon" />

      <title>Messenger Clone</title>
    </>
  );
}
